version: "3"

services:
  db:
    image: postgres:14-alpine
    env_file: .env
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_USER=go-crm
      - POSTGRES_PASSWORD=go-crm
      - POSTGRES_DB=go-crm
    ports:
      - "5432:5432"

  migrate-db:
      image: postgres:14-alpine
      env_file: .env
      container_name: migrate-db
      volumes:
        - pgdata-migrate:/var/lib/postgresql/data
      restart: on-failure
      environment:
        - POSTGRES_USER=migrate-db
        - POSTGRES_PASSWORD=migrate-db
        - POSTGRES_DB=migrate-db
      ports:
        - "5431:5432"

  redis:
    image: bitnami/redis:latest
    env_file: .env
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"


volumes:
  pgdata:
  pgdata-migrate:
